name: Maven Build

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK (for Maven to run)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Step 3: Build Maven project
    - name: Build with Maven
      run: mvn clean install

    # Step 4: Display output for each Maven goal (execute all goals)
    - name: Display output of all Maven goals
      run: |
        mvn validate
        mvn compile
        mvn test
        mvn package
        mvn verify
        mvn install
        mvn deploy
        mvn site
        mvn clean
